services:
  - type: web
    name: valence-task-bot
    repo: https://github.com/peacedestroyer69/valence-task-bot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python task_bot.py
    healthCheckPath: /health
    envVars:
      - key: TASK_BOT_TOKEN
        sync: false
      - key: FIREBASE_CREDENTIALS
        sync: false
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: GUILD_ID
        sync: false
